config/routes.rb
Rails.application.routes.draw do
  resources :cards
  resources :lanes
  devise_for :users

  resources :boards do
    resources :lanes do
      resources :cards do
        resources :tasks
      end
    end
  end

  root 'home#index'
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  completed  :boolean          default("0")
#  card_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Task < ApplicationRecord
  belongs_to :card

  broadcasts_to ->(task) { [task.card, :tasks] }, target: ->(task) { "card_#{task.card.id}_tasks" }
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_parents
  before_action :set_task, only: %i[show edit update destroy]

  # GET /tasks or /tasks.json
  def index
    @tasks = @card.tasks
  end

  # GET /tasks/1 or /tasks/1.json
  def show; end

  # GET /tasks/new
  def new
    @task = @card.tasks.new
  end

  # GET /tasks/1/edit
  def edit; end

  # POST /tasks or /tasks.json
  def create
    @task = @card.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.turbo_stream do
          render turbo_stream:
            [
              turbo_stream.replace("card_#{@lane.id}_new_task", partial: 'tasks/new_task_button',
                                                                locals: { card: @card }),
              turbo_stream.replace(@card, partial: 'cards/card', locals: { card: @card })
            ]
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(@card, partial: 'cards/card', locals: { card: @card })
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(@card, partial: 'cards/card', locals: { card: @card })
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = @card.tasks.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def task_params
    params.require(:task).permit(:title, :completed)
  end

  def set_parents
    @board = Board.find(params[:board_id])
    @lane = @board.lanes.find(params[:lane_id])
    @card = @lane.cards.find(params[:card_id])
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: task, url: [@board, @lane, @card, task], class: "contents") do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 rounded-lg mt-3">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mt-5">
    <%= form.text_field :title, placeholder: 'Task Name', class: "text-xs text-field" %>
  </div>

  <div class="mt-3">
    <%= form.submit class: "submit-btn" %>
    <% if action_name == "edit" %>
      <%= link_to 'Cancel', board_lane_card_task_path(@board, @lane, @card, task), class: 'text-xs' %>
    <% else %>
      <%= link_to 'Cancel', board_lane_card_path(@board, @lane, @card), class: 'text-xs' %>
    <% end %>
  </div>
<% end %>

app/views/tasks/_new_task_button.html.erb
<%= turbo_frame_tag "card_#{card.id}_new_task" do %>
  <%= button_to 'New Task', new_board_lane_card_task_path(card.lane.board, card.lane, card), method: :get, class: "submit-btn mt-3" %>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <span
      class="task <%= task.completed? ? 'line-through' : '' %>"
      >
      <input
          type="checkbox"
          data-cards-target="checkbox"
          data-action="click->tasks#click click->cards#countTasks"
          data-tasks-path-param="<%= board_lane_card_task_path(task.card.lane.board, task.card.lane, task.card, task) %>"
          class="rounded mr-2" <%= task.completed? ? 'checked' : ''%>
        >
        <%= task.title %>
        <%= button_to board_lane_card_task_path(task.card.lane.board, task.card.lane, task.card, task),
          method: :delete,
          class: 'pl-2 delete-btn',
          data: {
            confirmation_target: "elements",
            message: "Are you sure?",
            controller: "confirmation",
            action: "click->confirmation#confirm"
          } do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
          </svg>
        <% end %>
  </span>
</div>

app/views/tasks/create.turbo_stream.erb
<%= turbo_stream.replace :new_card, partial: 'tasks/new_task_button', locals: {card: @task.card} %>

app/views/tasks/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing task</h1>

  <%= render "form", task: @task %>

  <%= link_to "Show this task", @task, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to tasks", tasks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/tasks/new.html.erb
<%= turbo_frame_tag "card_#{@task.card.id}_new_task" do %>
  <%= render "form", task: @task %>
<% end %>

app/views/tasks/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @task %>

    <%= link_to 'Edit this task', edit_task_path(@task), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this task', task_path(@task), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to tasks', tasks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>