config/routes.rb
Rails.application.routes.draw do
  resources :cards
  resources :lanes
  devise_for :users

  resources :boards do
    resources :lanes do
      resources :cards do
        resources :tasks
      end
    end
  end

  root 'home#index'
end

app/models/lane.rb
# == Schema Information
#
# Table name: lanes
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  board_id   :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Lane < ApplicationRecord
  belongs_to :board
  has_many :cards, dependent: :destroy

  broadcasts_to ->(lane) { [lane.board, :lanes] }, target: ->(lane) { "board_#{lane.board.id}_lanes" }
end

app/controllers/lanes_controller.rb
class LanesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_board
  before_action :set_lane, only: %i[show edit update destroy]

  # GET /lanes or /lanes.json
  def index
    @lanes = @board.lanes
  end

  # GET /lanes/1 or /lanes/1.json
  def show; end

  # GET /lanes/new
  def new
    @lane = @board.lanes.new
  end

  # GET /lanes/1/edit
  def edit; end

  # POST /lanes or /lanes.json
  def create
    @lane = @board.lanes.new(lane_params)

    respond_to do |format|
      if @lane.save
        format.turbo_stream do
          turbo_stream.replace :new_lane, partial: 'lanes/new_lane_button', locals: { board: @board }
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lanes/1 or /lanes/1.json
  def update
    respond_to do |format|
      if @lane.update(lane_params)
        format.turbo_stream
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lanes/1 or /lanes/1.json
  def destroy
    @lane.destroy

    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_lane
    @lane = Lane.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def lane_params
    params.require(:lane).permit(:title)
  end

  def set_board
    @board = Board.find(params[:board_id])
  end
end

app/helpers/lanes_helper.rb
module LanesHelper
end

app/views/lanes/_form.html.erb
<%= form_with(model: lane, url: [@board, lane], class: "contents") do |form| %>
  <% if lane.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 rounded-lg mt-3">
      <h2><%= pluralize(lane.errors.count, "error") %> prohibited this lane from being saved:</h2>

      <ul>
        <% lane.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-1">
    <%= form.text_field :title, placeholder: 'Lane Title', class: "text-field" %>
  </div>

  <div class="my-3">
    <%= form.submit class: "submit-btn" %>
    <% if action_name == "edit" %>
      <%= link_to 'Cancel', board_lane_path(@board, lane), class: 'text-xs' %>
    <% else %>
      <%= link_to 'Cancel', board_path(@board), class: 'text-xs' %>
    <% end %>
  </div>
<% end %>

app/views/lanes/_lane.html.erb
<%= turbo_stream_from lane, :cards %>

<div id="<%= dom_id lane %>" class="rounded bg-gray-200 w-64 p-2">
  <%= turbo_frame_tag "lane_#{lane.id}_frame" do %>
    <div class="py-1">
      <%= button_to board_lane_path(lane.board, lane),
        method: :delete,
        class: 'delete-btn float-right',
        data: {
          confirmation_target: "elements",
          message: "Are you sure?",
          controller: "confirmation",
          action: "click->confirmation#confirm"
        } do %>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
        </svg>
      <% end %>
      <%= link_to lane.title, edit_board_lane_path(lane.board, lane) %>
    </div>

    <div id="lane_<%= lane.id %>_cards" class="text-sm mt-2">
      <%= render lane.cards %>
    </div>

    <%= render partial: 'cards/new_card_button', locals: {lane: lane} %>

  <% end %>
</div>

app/views/lanes/_new_lane_button.html.erb
<%= turbo_frame_tag :new_lane do %>
  <%= button_to 'New Lane', new_board_lane_path(board), method: :get, class: "submit-btn mb-3" %>
<% end %>

app/views/lanes/edit.html.erb
<%= turbo_frame_tag "lane_#{@lane.id}_frame" do %>
  <%= render "form", lane: @lane %>
<% end %>

app/views/lanes/new.html.erb
<%= turbo_frame_tag :new_lane do %>
  <div class="lane">
    <%= render "form", lane: @lane %>
  </div>
<% end %>

app/views/lanes/show.html.erb
<%= render @lane %>