config/routes.rb
Rails.application.routes.draw do
  resources :cards
  resources :lanes
  devise_for :users

  resources :boards do
    resources :lanes do
      resources :cards do
        resources :tasks
      end
    end
  end

  root 'home#index'
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id              :integer          not null, primary key
#  user_id         :integer          not null
#  title           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  organization_id :integer
#

class Board < ApplicationRecord
  belongs_to :user
  belongs_to :organization, optional: true
  has_many :lanes, dependent: :destroy

  broadcasts_to ->(board) { [board.user, :boards] }

  before_create do
    self.organization = user.organization if user.organization
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_board, only: %i[show edit update destroy]

  # GET /boards or /boards.json
  def index
    @boards = current_user.boards
    @organization_boards = (current_user.organization&.boards || []) - current_user.boards
  end

  # GET /boards/1 or /boards/1.json
  def show; end

  # GET /boards/new
  def new
    @board = current_user.boards.new
  end

  # GET /boards/1/edit
  def edit; end

  # POST /boards or /boards.json
  def create
    @board = current_user.boards.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to board_url(@board), notice: 'Board was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1 or /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to board_url(@board), notice: 'Board was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1 or /boards/1.json
  def destroy
    @board.destroy

    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_board
    @board = Board.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def board_params
    params.require(:board).permit(:title)
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_board.html.erb
<div id="<%= dom_id board %>" class="lg:w-1/3 md:w-1/2 w-full p-4 ">
  <div class="p-8 rounded-xl border border-gray-200 bg-white">
    <h4>
      <%= board.title %>
      <% if board.user == current_user %>
        <%= link_to edit_board_path(board), class: "inline-block" do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
          </svg>
        <% end %>
      <% end %>
    </h4>
    <hr />
    <% if action_name != "show" %>
      <%= button_to "Show", board, method: :get, class: "my-4 px-4 py-2 block w-full text-white bg-blue-500 hover:bg-blue-700 rounded" %>
    <% end %>
  </div>
</div>

app/views/boards/_form.html.erb
<%= form_with(model: board, class: "contents") do |form| %>
  <% if board.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
        <% board.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", maxlength: 255 %>
  </div>

  <div class="inline">
    <%= form.submit 'Rename Board', class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing board</h1>

  <%= render "form", board: @board %>

  <%= link_to "Show this board", @board, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to boards", boards_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/boards/index.html.erb
<%= turbo_stream_from [current_user, :boards] %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl"><%= current_user.belongs_to_organization? ? 'My Boards' : 'Boards' %></h1>
    <%= link_to 'New board', new_board_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <section id="boards" class="container w-full mx-auto flex flex-wrap">
    <%= render @boards %>
  </section>

  <% if current_user.belongs_to_organization? %>
    <div class="py-5">
      <div class="flex justify-between items-center">
        <h1 class="font-bold text-4xl">Organization Boards</h1>
      </div>

      <section id="organization_boards" class="container w-full mx-auto flex flex-wrap">
        <%= render @organization_boards %>
      </section>
    </div>
  <% end %>
</div>

app/views/boards/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New board</h1>

  <%= render "form", board: @board %>

  <%= link_to 'Back to boards', boards_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/boards/show.html.erb
<%= turbo_stream_from @board, :lanes %>

<div class="mx-auto w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <%= link_to '<< Back to boards', boards_path %>

  <h1 class="text-center m-3 text-2xl font-bold"><%= @board.title %></h1>

  <div class="w-1/3">
    <%= render partial: 'lanes/new_lane_button', locals: {board: @board} %>
  </div>

  <div id="board_<%= @board.id %>_lanes" class="flex gap-2 bg-blue-400 p-8 font-sans rounded">
    <%= render @board.lanes %>
  </div>
</div>