config/routes.rb
Rails.application.routes.draw do
  resources :cards
  resources :lanes
  devise_for :users

  resources :boards do
    resources :lanes do
      resources :cards do
        resources :tasks
      end
    end
  end

  root 'home#index'
end

app/models/card.rb
# == Schema Information
#
# Table name: cards
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  description :text(65535)
#  lane_id     :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Card < ApplicationRecord
  belongs_to :lane
  has_many :tasks, dependent: :destroy

  broadcasts_to ->(card) { [card.lane, :cards] }, target: ->(card) { "lane_#{card.lane.id}_cards" }

  def completed?
    tasks.all?(&:completed?)
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_parents
  before_action :set_card, only: %i[show edit update destroy]

  # GET /cards or /cards.json
  def index
    @cards = @lane.cards.all
  end

  # GET /cards/1 or /cards/1.json
  def show; end

  # GET /cards/new
  def new
    @card = @lane.cards.new
  end

  # GET /cards/1/edit
  def edit; end

  # POST /cards or /cards.json
  def create
    @card = @lane.cards.new(card_params)

    respond_to do |format|
      if @card.save
        format.turbo_stream do
          turbo_stream.replace "lane_#{@lane.id}_new_card", partial: 'cards/new_card_button', locals: { lane: @lane }
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1 or /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.turbo_stream
      else
        format.html do
          render :edit, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /cards/1 or /cards/1.json
  def destroy
    @card.destroy
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_card
    @card = @lane.cards.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def card_params
    params.require(:card).permit(:title, :description)
  end

  def set_parents
    @board = Board.find(params[:board_id])
    @lane = @board.lanes.find(params[:lane_id])
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_card.html.erb
<%= turbo_stream_from card, :tasks %>

<div
  id="<%= dom_id card %>"
  class="card <%= card.tasks.empty? ? '' : (card.completed? ? 'completed' : 'incomplete') %>"
  data-controller="cards"
  data-cards-target="card"
  >
  <%= turbo_frame_tag "card_#{card.id}_frame" do %>
    <%= button_to board_lane_card_path(card.lane.board, card.lane, card),
      method: :delete,
      class: 'delete-btn float-right',
      data: {
        confirmation_target: "elements",
        message: "Are you sure?",
        controller: "confirmation",
        action: "click->confirmation#confirm"
      } do %>
      <svg xmlns="http://www.w3.org/2000/svg" class="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
      </svg>
    <% end %>
    <%= link_to card.title, edit_board_lane_card_path(card.lane.board, card.lane, card) %>
    <span class="text-xs" data-cards-target="count"></span>

    <p class="text-xs"><%= simple_format(card.description) %></p>

    <div id="card_<%= card.id %>_tasks" data-controller="tasks" class="text-grey-darker mt-2 ml-2">
      <%= render card.tasks %>
    </div>

    <%= render partial: 'tasks/new_task_button', locals: {card: card} %>
  <% end %>
</div>

app/views/cards/_form.html.erb
<%= form_with(model: card, url: [@board, @lane, card], class: "contents") do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 rounded-lg mt-3">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
        <% card.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mt-1">
    <%= form.text_field :title, placeholder: 'Card Title', class: "text-field" %>
  </div>

  <div class="mt-1">
    <%= form.text_area :description, class: "text-area" %>
  </div>

  <div class="mt-3">
    <%= form.submit class: "submit-btn" %>
    <% if action_name == "edit" %>
      <%= link_to 'Cancel', board_lane_card_path(@board, @lane, card), class: 'text-xs' %>
    <% else %>
      <%= link_to 'Cancel', board_lane_path(@board, @lane), class: 'text-xs' %>
    <% end %>
  </div>
<% end %>

app/views/cards/_new_card_button.html.erb
<%= turbo_frame_tag "lane_#{lane.id}_new_card" do %>
  <%= button_to 'New Card', new_board_lane_card_path(lane.board, lane), method: :get, class: "submit-btn mt-3" %>
<% end %>

app/views/cards/create.turbo_stream.erb
<%= turbo_stream.replace :new_card, partial: 'cards/new_card_button', locals: {lane: @card.lane} %>

app/views/cards/edit.html.erb
<%= turbo_frame_tag "card_#{@card.id}_frame" do %>
  <%= render "form", card: @card %>
<% end %>

app/views/cards/new.html.erb
<%= turbo_frame_tag "lane_#{@card.lane.id}_new_card" do %>
  <div class="card">
    <%= render "form", card: @card %>
  </div>
<% end %>

app/views/cards/show.html.erb
<%= render @card %>